name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/setup

      - name: copy env
        shell: bash
        run: cp .env.example .env

      - name: Lint
        run: npm run lint
        
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4

      - name: Setup
        uses: ./tooling/setup

      - name: Format
        run: npm run format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/setup

      - name: Typecheck
        run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/setup

      - name: Test (Vitest)
        run: npm run test
    

      
